# Generated by Django 5.2.8 on 2025-11-15 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Starship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("model", models.CharField(max_length=200)),
                ("manufacturer", models.CharField(max_length=200)),
                ("cost_in_credits", models.CharField(max_length=100)),
                ("length", models.CharField(max_length=100)),
                ("max_atmosphering_speed", models.CharField(max_length=100)),
                ("crew", models.CharField(max_length=100)),
                ("passengers", models.CharField(max_length=100)),
                ("cargo_capacity", models.CharField(max_length=100)),
                ("starship_class", models.CharField(max_length=200)),
                ("url", models.URLField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
